"""Official Hong Kong, Macao and Taiwan legal references.

These are curated starter references, not exhaustive registers or legal advice.
The sources are official legislation portals or government regulators. Summaries
are editorial paraphrases and each entry states its territorial/subject limits.
"""

from __future__ import annotations


ALL_INDUSTRIES = [
    "food-beverage", "manufacturing", "commerce", "saas", "logistics",
    "construction", "healthcare", "professional-services", "finance-services",
    "property", "education", "agriculture", "energy-utilities", "general-enterprise",
]


def _reference(
    id: str, title: str, authority: str, category: str,
    country_code: str, country_name: str, jurisdiction: str,
    summary: str, obligations: list[str], process_tags: list[str],
    industries: list[str], source_url: str, scope_note: str,
    domain_keys: list[str], effective_date: str | None = None,
) -> dict:
    return {
        "id": id,
        "title": title,
        "authority": authority,
        "category": category,
        "country_code": country_code,
        "country_name": country_name,
        "jurisdiction": jurisdiction,
        "status": "官方法规来源索引；适用前核对现行文本及生效状态",
        "source_kind": "法律/条例",
        "effective_date": effective_date,
        "summary": summary,
        "obligations": obligations,
        "process_tags": process_tags,
        "industry_keys": list(industries),
        "source_url": source_url,
        "scope_note": scope_note,
        "checked_on": "2026-10-02",
        "domain_keys": domain_keys,
    }


HK = ("HK", "香港特别行政区", "香港特别行政区·全域")
MO = ("MO", "澳门特别行政区", "澳门特别行政区·全域")
TW = ("TW", "台湾地区", "台湾地区·全域")


REGIONAL_EXTENSIONS = [
    # Hong Kong
    _reference(
        "hk-personal-data-privacy", "个人资料（私隐）条例（第486章）",
        "香港个人资料私隐专员公署 / 香港电子法例", "数据与隐私",
        *HK,
        "规范资料使用者收集、持有、处理及使用个人资料的目的、告知、安全、保存和查阅安排。",
        ["说明收集目的及资料类别，核对资料是否足够但不过量。", "限制目的外使用；落实资料准确性、保存期限、访问权限和安全保障。", "建立查阅/改正请求及资料外泄事件的评估、应变和记录流程。"],
        ["客户资料", "员工人事", "会员营销", "患者信息", "数据导出", "安全事件"],
        ALL_INDUSTRIES,
        "https://www.elegislation.gov.hk/hk/cap486!en",
        "香港境内个人资料处理的主要法例；须依资料使用者、处理活动和法定豁免核对。2021年修订增加未经同意披露个人资料等规则；跨境转移条文的生效状态及其他最新修订须查官方现行文本。",
        ["privacy", "people"],
    ),
    _reference(
        "hk-companies-ordinance", "公司条例（第622章）",
        "香港公司注册处 / 香港电子法例", "公司治理",
        *HK,
        "规范香港公司成立、组织、董事责任、成员权利、会计及审计、申报和公司记录等事项。",
        ["按公司类型维护法定登记册、董事/成员决议和周年申报日历。", "落实董事会及授权记录、会计记录、财务报表和审计安排。", "重要控制人登记册等法定义务按公司类别和豁免条件核对。"],
        ["公司治理", "授权审批", "财务报告", "法定登记", "受益所有权"],
        ALL_INDUSTRIES,
        "https://www.cr.gov.hk/en/legislation/companies-ordinance/cap622/companies-ordinance.htm",
        "主要适用于按香港法例成立的公司，部分规定亦涉及注册非香港公司；具体申报和豁免依公司类别、规模及现行条文确认。该页面由公司注册处提供，并链接至电子法例全文。",
        ["governance", "finance"],
    ),
    _reference(
        "hk-employment-ordinance", "雇佣条例（第57章）",
        "香港劳工处 / 香港电子法例", "劳动用工",
        *HK,
        "香港雇佣条件和雇员法定权益的主要条例，涵盖工资、休息日、有薪假期、疾病津贴及终止雇佣等。",
        ["保存工资、雇佣条件、工时/假期及终止雇佣相关记录。", "核对工资支付、法定假日、休息日、年假及雇佣保障的适用要求。", "管理雇佣合约、员工类别和例外情况，并及时更新薪酬与休假参数。"],
        ["员工入职", "薪酬核算", "工时排班", "假期管理", "离职结算"],
        ALL_INDUSTRIES,
        "https://www.labour.gov.hk/eng/legislat/content2.htm",
        "适用于香港雇佣关系，雇佣条例对若干类别设有例外或特别安排；劳工处网页为官方概览，具体权利、金额和记录期限须查现行条例及附属规例。",
        ["people", "governance"],
    ),
    _reference(
        "hk-occupational-safety-health", "职业安全及健康条例（第509章）",
        "香港劳工处 / 香港电子法例", "职业安全",
        *HK,
        "为工业及非工业工作场所雇员提供安全与健康保护，规定雇主、处所占用人及雇员的职责。",
        ["识别工作场所危害，提供安全工作系统、设备、培训、监督及安全出入通道。", "占用处所者评估场地、出入通道、设备及物质对工作者的风险。", "记录事故、检查、培训、纠正措施和监管通知的跟进。"],
        ["生产作业", "施工安全", "设备维护", "场所巡检", "事故报告"],
        ["food-beverage", "manufacturing", "logistics", "construction", "healthcare", "property", "education", "agriculture", "energy-utilities", "general-enterprise"],
        "https://www.labour.gov.hk/eng/legislat/content4.htm",
        "涵盖大多数工业及非工业工作场所；条例规定少数例外（例如仅由自雇人士工作的场所）。施工、工厂、锅炉等另有专项法例和规例。劳工处网页为官方说明，具体要求以现行法例为准。",
        ["safety", "people"],
    ),
    _reference(
        "hk-food-safety-ordinance", "食物安全条例（第612章）",
        "香港食物环境卫生署食物安全中心", "食品安全与追溯",
        *HK,
        "建立食物进口商及分销商登记，以及食物流转记录制度，支持食品追溯和风险食品召回。",
        ["确认食物进口商/分销商登记义务及法定豁免。", "保存可追踪食物流转的资料，确保供应商、批次、交易和去向可还原。", "建立问题食品停售、回收、监管命令和事件升级机制。"],
        ["供应商准入", "食材验收", "批次追溯", "食品进口", "食品召回"],
        ["food-beverage", "agriculture", "manufacturing", "commerce", "logistics"],
        "https://www.cfs.gov.hk/tc_chi/foodsafetyordinance/food_safety_ordinance.html",
        "于2012-02-01全面实施；登记和记录义务须依经营角色及法定豁免判断。本条例是香港食物法例的一部分，不替代公共卫生及市政服务条例下的其他食品规则。",
        ["quality", "safety", "procurement", "trade"], "2012-02-01",
    ),
    _reference(
        "hk-trade-descriptions-ordinance", "商品说明条例（第362章）",
        "香港海关 / 香港电子法例", "消费者权益与公平交易",
        *HK,
        "规管商品及服务的虚假商品说明、误导性遗漏、具威吓性的营业行为和其他不良营商手法。",
        ["审核商品/服务说明、价格、促销条件、供应信息及重要限制，确保准确且不具误导性。", "审查标准合约、自动续费、销售话术和投诉处理中的不公平或具威吓性做法。", "保存广告版本、批准记录、交易证明和投诉纠正记录。"],
        ["商品上架", "营销宣传", "订单履约", "退款售后", "客户投诉"],
        ["commerce", "food-beverage", "manufacturing", "saas", "education", "professional-services", "healthcare", "property", "general-enterprise"],
        "https://www.customs.gov.hk/hcms/filemanager/en/content_189/tdo_e.pdf",
        "香港海关官方资料说明条例及修订后的消费者保障范围；个别禁止行为、例外及适用交易应以第362章现行正文和附属法例核对。香港没有单一覆盖所有交易问题的综合消费者法，行业法例亦须另查。",
        ["sales", "quality"],
    ),

    # Macao
    _reference(
        "mo-commercial-code", "商法典（第40/99/M号法令核准）",
        "澳门特别行政区公报 / 法务局 LegisMac", "公司治理与商事会计",
        *MO,
        "规范商业企业、公司、商行为、商事登记、商业记账及年度账目等商事活动基础事项。",
        ["按组织形态维护公司设立、章程、机关决议、商业登记和授权资料。", "建立符合商业记账和年度账目要求的会计记录及凭证保存安排。", "公司治理、出资、股东权利及申报义务按公司类型核对。"],
        ["公司治理", "授权审批", "商业登记", "财务报告", "账簿凭证"],
        ALL_INDUSTRIES,
        "https://bo.dsaj.gov.mo/bo/i/99/31/codcomcn/codcom0001.asp",
        "适用于澳门商业企业及商事活动的相关主体；官方法规页提示商法典已经历修订，特别包括第27/2024号法律的适应化及整合。应使用官方现行整合文本并按组织形态核对。",
        ["governance", "finance"],
    ),
    _reference(
        "mo-personal-data-protection", "个人资料保护法（第8/2005号法律）",
        "澳门特别行政区公报 / 个人资料保护局", "数据与隐私",
        *MO,
        "确立澳门个人资料处理及保护制度，涵盖自动化处理和纳入人工资料库的非自动化处理。",
        ["明确处理目的、法律依据及资料类别，告知资料当事人相关事项。", "保障资料查阅/更正等权利，并对资料使用、保存、安全和对外提供实施控制。", "审查委托处理、录影监视及跨境资料传输是否触发特别条件或通知/许可要求。"],
        ["客户资料", "员工人事", "患者信息", "监控录影", "第三方处理", "数据导出"],
        ALL_INDUSTRIES,
        "https://bo.dsaj.gov.mo/bo/i/2005/34/lei08_cn.asp",
        "适用于法定范围内在澳门进行的个人资料处理；法例对个人/家庭活动、公共安全及其他特别情形设有适用规则。跨境传输、敏感资料和影像监控应按现行文本及个人资料保护局指引逐案核对。",
        ["privacy", "people"],
    ),
    _reference(
        "mo-labour-relations-law", "劳动关系法（第7/2008号法律）",
        "澳门特别行政区公报 / 劳工事务局", "劳动用工",
        *MO,
        "规定澳门劳动关系的一般制度，涉及劳动合同、工作时间、休息、报酬、假期、终止关系及相关保障。",
        ["建立书面劳动条件及员工档案，准确计算报酬、工作时间、休息和假期。", "按法定条件处理超时工作、缺勤、终止劳动关系及相关补偿。", "跟踪修订及重新公布文本，确保人事制度、薪资系统和合同模板一致。"],
        ["员工入职", "劳动合同", "薪酬核算", "工时排班", "离职结算"],
        ALL_INDUSTRIES,
        "https://bo.dsaj.gov.mo/bo/i/2008/33/lei07_cn.asp",
        "适用于澳门劳动关系；部分规定或条文可能设有特别范围。公报注记该法经第134/2020号行政长官批示重新公布，且多次修改；具体义务请对照现行整合文本及劳工事务局说明。",
        ["people", "governance"], "2009-01-01",
    ),
    _reference(
        "mo-food-safety-law", "食品安全法（第5/2013号法律）",
        "澳门特别行政区公报 / 市政署", "食品安全与追溯",
        *MO,
        "规管澳门食品生产经营监督、风险预防与控制、事故处理和问题食品召回。",
        ["建立有效的食品安全内部管理制度，按食品安全标准从事生产经营。", "在指定期间保存进货、出货记录或相关单据，确保来源和去向可追踪。", "发现或可能存在食品安全风险时依法通报，并适时召回问题食品。"],
        ["供应商准入", "食材验收", "批次追溯", "冷链温控", "食品召回"],
        ["food-beverage", "agriculture", "manufacturing", "commerce", "logistics"],
        "https://bo.dsaj.gov.mo/bo/i/2013/17/lei05_cn.asp",
        "适用于澳门食品生产经营及相关食品添加剂、食品相关产品使用；药物等法定排除项除外。相关限量和标准由补充法规持续细化，需同时检查现行附属法规及产品类别。",
        ["quality", "safety", "procurement", "trade"],
    ),
    _reference(
        "mo-consumer-protection-law", "消费者权益保护法（第9/2021号法律）",
        "澳门特别行政区公报 / 消费者委员会", "消费者权益",
        *MO,
        "保护澳门经营者与消费者之间的商品或服务交易关系，涵盖安全、质量、交易信息及公平营商。",
        ["提供清楚、真实的商品/服务、价格、交易条件和风险信息。", "审核格式合同、销售做法、交付及退换/投诉处理安排。", "建立消费争议受理、转介、答复和纠正问题的记录。"],
        ["商品上架", "合同审查", "营销宣传", "退款售后", "客户投诉"],
        ["commerce", "food-beverage", "manufacturing", "saas", "education", "professional-services", "healthcare", "property", "general-enterprise"],
        "https://bo.dsaj.gov.mo/bo/i/2021/28/lei09_cn.asp",
        "适用于经营者在澳门从事业务并在澳门交付/寄送商品或提供服务而形成的消费者关系；远程交易须按法定连接条件判断。行业另有特别消费者法例时应一并核对。",
        ["sales", "quality"],
    ),
    _reference(
        "mo-cybersecurity-law", "网络安全法（第13/2019号法律）",
        "澳门特别行政区公报 / 司法警察局网络安全委员会", "网络与系统安全",
        *MO,
        "建立澳门网络安全体系，重点规管关键基础设施营运者所使用的信息网络、电脑系统和电脑数据。",
        ["先确认组织、营运服务及设施是否被纳入法定关键基础设施范围。", "适用时落实网络安全技术规范、事故预警/应对/通报及责任人机制。", "将监管通告、技术规范和整改复核记录关联到系统、服务和营运者。"],
        ["信息系统运维", "关键系统", "供应商管理", "安全事件", "业务连续性"],
        ["saas", "finance-services", "healthcare", "logistics", "energy-utilities", "property", "general-enterprise"],
        "https://bo.dsaj.gov.mo/bo/i/2019/25/lei13_cn.asp",
        "本法核心义务针对澳门法定关键基础设施营运者，并非所有企业的一般网络安全法。须确认是否属于法定行业/营运者及适用技术规范；一般企业仍需另行评估个人资料、行业许可和合同要求。",
        ["privacy", "safety", "procurement"],
    ),

    # Taiwan
    _reference(
        "tw-company-act", "公司法",
        "台湾法务部全国法规资料库", "公司治理",
        *TW,
        "规定公司组织形态、设立、股东/董事权责、资本、财务会计及公司登记等事项。",
        ["按公司类型履行设立、登记变更、股东会/董事会及法定簿册要求。", "落实董事权限、关联交易、资本变动和重大决策的审批与留痕。", "依据适用公司类型和规定处理财务报告、盈余分派及法定申报。"],
        ["公司治理", "授权审批", "董事会决议", "关联交易", "财务报告"],
        ALL_INDUSTRIES,
        "https://law.moj.gov.tw/LawClass/LawAll.aspx?pcode=J0080001",
        "适用于依台湾地区法规设立的公司；有限公司、股份有限公司等组织形态的治理及申报要求不同。境外公司在台分公司或办事处另核对相关规定。",
        ["governance", "finance"],
    ),
    _reference(
        "tw-personal-data-protection-act", "个人资料保护法",
        "台湾法务部全国法规资料库 / 个人资料保护委员会筹备处", "数据与隐私",
        *TW,
        "规范公务机关及非公务机关个人资料的蒐集、处理、利用、资料当事人权利及安全维护。",
        ["确认蒐集目的、法律依据、资料类别及告知事项，遵守目的必要范围。", "建立查询、更正、停止利用和删除请求的受理及时限管理。", "落实资料安全维护、委托处理和事故通报/通知要求。"],
        ["客户资料", "员工人事", "会员营销", "患者信息", "第三方处理", "安全事件"],
        ALL_INDUSTRIES,
        "https://law.moj.gov.tw/LawClass/LawAll.aspx?pcode=I0050021",
        "适用于台湾地区法定范围内的个人资料处理。全国法规资料库当前页面显示2025-11-11修正条文中部分条文尚未生效、施行日未定；本索引按已生效文本理解，实施前须核实各条实际生效状态及主管机关公告。",
        ["privacy", "people"],
    ),
    _reference(
        "tw-labor-standards-act", "劳动基准法",
        "台湾法务部全国法规资料库 / 劳动部", "劳动用工",
        *TW,
        "规定劳动条件最低标准，涵盖劳动契约、工资、工时、休息休假、未成年劳动者、退休及终止等事项。",
        ["确认劳动者类别和适用/排除行业，依规定建立劳动契约及出勤、工资记录。", "校验正常工时、延长工时、休息、例假/休假及工资计算。", "离职、资遣、退休和职业灾害相关事项按适用规则处理并留存记录。"],
        ["员工入职", "劳动合同", "薪酬核算", "工时排班", "离职结算"],
        ALL_INDUSTRIES,
        "https://law.moj.gov.tw/LawClass/LawAll.aspx?pcode=N0030001",
        "适用范围依劳动关系、行业和法定例外判断；特定行业、职业类别及弹性工时安排另有条件，须核对现行条文、公告和劳动部解释。",
        ["people", "governance"],
    ),
    _reference(
        "tw-occupational-safety-health-act", "职业安全卫生法",
        "台湾法务部全国法规资料库 / 劳动部", "职业安全",
        *TW,
        "规范工作场所安全卫生设施、危害预防、健康保护、承揽管理及职业灾害通报等事项。",
        ["辨识工作场所危害并依规模/行业设立安全卫生管理、设备和教育训练。", "对承揽、共同作业、危险机械设备及有害物质落实资格审查和风险控制。", "建立职业灾害调查、法定通报、原因分析、改善和复核记录。"],
        ["生产作业", "施工安全", "设备维护", "承包商管理", "事故报告"],
        ["food-beverage", "manufacturing", "logistics", "construction", "healthcare", "property", "agriculture", "energy-utilities", "general-enterprise"],
        "https://law.moj.gov.tw/LawClass/LawAll.aspx?pcode=N0060001",
        "适用于台湾地区法定工作者和事业单位范围；行业、危险作业、承揽结构及主管机关指定事项会影响具体义务。应同时核对施行细则及行业安全卫生规则。",
        ["safety", "people"],
    ),
    _reference(
        "tw-food-safety-sanitation-act", "食品安全卫生管理法",
        "台湾法务部全国法规资料库 / 卫生福利部食品药物管理署", "食品安全与追溯",
        *TW,
        "规范食品及食品添加物等的卫生安全、业者管理、标示广告、输入、检验查核和风险处置。",
        ["确认食品业者登记、许可及食品类别要求，建立卫生自主管理和追溯制度。", "核对原料来源、产品标示、添加物、检验及生产/进口记录。", "发现风险或不合格食品时启动停售、回收、通报及矫正措施。"],
        ["供应商准入", "食材验收", "食品生产", "批次追溯", "食品进口", "食品召回"],
        ["food-beverage", "agriculture", "manufacturing", "commerce", "logistics"],
        "https://law.moj.gov.tw/LawClass/LawAll.aspx?pcode=L0040001",
        "适用于台湾地区食品及相关产品生产、制造、加工、调配、包装、运送、贮存、贩卖、输入/输出等法定活动。产品类别、业者规模和授权子法会影响注册、追溯及特别管理要求。",
        ["quality", "safety", "procurement", "trade"],
    ),
    _reference(
        "tw-consumer-protection-act", "消费者保护法",
        "台湾法务部全国法规资料库 / 行政院消费者保护处", "消费者权益",
        *TW,
        "规范消费者交易安全、资讯提供、商品/服务责任、定型化契约及通讯交易等消费者保护事项。",
        ["审核商品/服务安全、说明、广告及交易条件，保存发布版本和审核记录。", "审查定型化契约公平性及依法公告的行业应记载/不得记载事项。", "在线/通讯交易提供必要资讯，建立退货、申诉、争议和安全回收流程。"],
        ["商品上架", "营销宣传", "合同审查", "订单履约", "退款售后", "客户投诉"],
        ["commerce", "food-beverage", "manufacturing", "saas", "education", "professional-services", "healthcare", "property", "general-enterprise"],
        "https://law.moj.gov.tw/LawClass/LawAll.aspx?pcode=J0170001",
        "适用于台湾地区消费者与企业经营者间的消费关系；消费者、交易目的及通讯/访问交易等适用条件须核实。特定行业公告的定型化契约规范和产品专法可能增加义务。",
        ["sales", "quality"],
    ),
    _reference(
        "tw-cybersecurity-management-act", "资通安全管理法",
        "台湾法务部全国法规资料库 / 数位发展部", "网络与系统安全",
        *TW,
        "规范公务机关及特定非公务机关的资通安全责任等级、防护计划、委外管理、稽核和事件通报。",
        ["确认主体是否为公务机关、关键基础设施提供者或其他法定特定非公务机关。", "适用时建立资安责任等级、维护计划、受托服务监督、演练及稽核整改。", "设置资安事件通报、调查、应变、改进报告和供应商协作流程。"],
        ["信息系统运维", "账号权限", "IT外包", "关键系统", "安全事件", "业务连续性"],
        ["saas", "finance-services", "healthcare", "logistics", "energy-utilities", "property", "general-enterprise"],
        "https://law.moj.gov.tw/LawClass/LawAll.aspx?pcode=A0030297",
        "主要义务适用于公务机关及法定特定非公务机关，包括经指定/核定的关键基础设施提供者等；并非一般民营企业一律适用。2025-09-24页面载有修正文本，须核查现行施行状态及主体指定结果。",
        ["privacy", "safety", "procurement"],
    ),
]
