"""Official overseas compliance references for country and process discovery.

Summaries are editorial Chinese paraphrases. A regulator's guidance is labelled
separately from legislation, and territorial/sector limits stay with each entry.
This module intentionally does not import compliance_library (avoid a cycle).
"""

from __future__ import annotations

_ALL_INDUSTRIES = [
    "food-beverage", "manufacturing", "commerce", "saas", "logistics",
    "construction", "healthcare", "professional-services", "finance-services",
    "property", "education", "agriculture", "energy-utilities", "general-enterprise",
]
_FOOD_INDUSTRIES = ["food-beverage", "agriculture", "manufacturing", "commerce", "logistics"]
_WORK_INDUSTRIES = ["food-beverage", "manufacturing", "logistics", "construction", "healthcare", "property", "agriculture", "energy-utilities", "general-enterprise"]


def _reference(
    id: str, title: str, authority: str, category: str,
    country_code: str, country_name: str, jurisdiction: str, source_kind: str,
    summary: str, obligations: list[str], process_tags: list[str],
    industry_keys: list[str], source_url: str, scope_note: str,
    domain_keys: list[str], effective_date: str | None = None,
) -> dict:
    return {
        "id": id, "title": title, "authority": authority, "category": category,
        "country_code": country_code, "country_name": country_name,
        "jurisdiction": jurisdiction, "source_kind": source_kind,
        "summary": summary, "obligations": obligations,
        "process_tags": process_tags, "industry_keys": list(industry_keys),
        "source_url": source_url, "scope_note": scope_note,
        "checked_on": "2026-10-02", "effective_date": effective_date,
        "domain_keys": domain_keys,
        "status": "官方来源索引；适用前核对现行版本",
    }


GLOBAL_EXTENSIONS = [
    _reference(
        "us-fsma-preventive-controls", "美国食品预防控制规则（FSMA / 21 CFR Part 117）",
        "美国食品药品监督管理局 FDA", "食品安全",
        "US", "美国", "美国·联邦／向美国供应食品", "监管指引",
        "FDA对人类食品设施的现行生产规范与风险预防控制要求，强调书面食品安全计划和危害预防。",
        ["识别生物、化学、物理等可合理预见危害，形成书面食品安全计划。", "按危害设置工艺、过敏原、卫生或供应链预防控制，实施监控、纠偏和验证。", "对需要预防控制的危害配置召回计划，保存控制执行记录。"],
        ["供应商准入", "食材验收", "食品生产", "过敏原管理", "食品召回"],
        _FOOD_INDUSTRIES,
        "https://www.fda.gov/food/food-safety-modernization-act-fsma/fsma-final-rule-preventive-controls-human-food",
        "通常适用于须按FD&C Act §415向FDA注册的美国或海外设施；农场、合格设施、零售餐饮及特定食品可能适用豁免或其他规则。先确认设施性质和适用子部分。链接为FDA规则说明。",
        ["procurement", "quality", "safety"],
    ),
    _reference(
        "us-osha-workplace", "美国职业安全健康法与OSHA雇主义务",
        "美国职业安全健康管理局 OSHA", "职业安全",
        "US", "美国", "美国·联邦及获批准州计划", "监管指引",
        "为美国工作场所建立风险防护、人员培训和事故记录的基础参考。",
        ["识别工作场所严重危害，落实适用OSHA标准、设备维护和安全操作要求。", "以员工能理解的语言提供培训；涉危险化学品时设置危害告知与安全数据表。", "按适用条件保存工伤记录、履行事故报告并跟踪整改。"],
        ["生产作业", "设备维护", "施工安全", "员工培训", "事故报告"],
        _WORK_INDUSTRIES,
        "https://www.osha.gov/workers/employer-responsibilities",
        "适用于多数美国私营雇主和员工，部分地区由获批准州计划执行。自雇、农场直系家属及其他联邦机构专管风险等存在例外；按地点和业务核对具体标准。",
        ["safety", "people"],
    ),
    _reference(
        "us-hipaa-security", "美国HIPAA安全规则（电子受保护健康信息）",
        "美国卫生与公众服务部 HHS", "医疗数据安全",
        "US", "美国", "美国·联邦／HIPAA受监管实体", "监管指引",
        "针对电子受保护健康信息ePHI配置管理、物理和技术保障措施。",
        ["确认是否属于受覆盖实体或业务伙伴，识别ePHI系统和处理活动。", "开展安全风险分析，控制访问、验证身份、记录活动并建立备份与应急措施。", "将员工培训及业务伙伴安全责任落实到制度、合同和执行记录。"],
        ["患者信息", "账号权限", "业务伙伴管理", "数据备份", "信息安全事件"],
        ["healthcare", "saas", "professional-services", "finance-services"],
        "https://www.hhs.gov/hipaa/for-professionals/security/laws-regulations/index.html",
        "限于HIPAA受覆盖实体及业务伙伴处理的ePHI，并非所有健康数据或一般雇主人事数据均适用；纸质/口头信息需另核对隐私规则。以现行法规为准，区分拟议修订和生效规则。",
        ["privacy", "safety", "procurement"],
    ),
    _reference(
        "us-ofac-sanctions", "美国OFAC制裁合规框架与交易筛查参考",
        "美国财政部外国资产控制办公室 OFAC", "制裁与跨境交易",
        "US", "美国", "美国·联邦／存在美国连接的交易", "监管指引",
        "以管理承诺、风险评估、内部控制、审查和培训构建制裁合规程序。",
        ["评估客户、供应商、地区、产品及支付渠道中的制裁风险。", "建立名单及所有权筛查、异常交易暂停和升级审批流程。", "定期检查控制效果、培训相关人员并保存筛查和决策证据。"],
        ["客户准入", "供应商准入", "跨境收付款", "订单审核", "贸易合规"],
        _ALL_INDUSTRIES,
        "https://ofac.treasury.gov/system/files/126/framework_ofac_cc.pdf",
        "此框架是监管参考，具体禁止、许可及阻断要求由各制裁项目决定。美国主体，以及涉及美国主体、商品服务或其他美国连接的境外业务须评估适用性；名单和项目应在交易时重新核对。",
        ["trade", "procurement", "sales", "finance", "governance"],
    ),
    _reference(
        "us-ear-export-controls", "美国出口管理条例（EAR）分类与许可",
        "美国商务部工业与安全局 BIS", "出口管制",
        "US", "美国", "美国·联邦／受EAR约束的跨境及境内转移", "监管指引",
        "将物项管辖判断、ECCN分类、目的地、最终用户与最终用途检查纳入订单履行。",
        ["先判断商品、软件或技术是否受EAR约束，记录ECCN或EAR99分类依据。", "结合目的地、最终用户、最终用途及限制核对许可要求。", "发货或技术提供前落实许可/例外核验与异常升级，定期复核分类。"],
        ["出口订单", "软件交付", "技术资料共享", "客户准入", "物流发运"],
        ["manufacturing", "commerce", "saas", "logistics", "energy-utilities", "professional-services"],
        "https://www.bis.gov/licensing/classify-your-item",
        "EAR可涉及再出口、境内转移及部分美国人员活动；EAR99并不自动免于所有限制。BIS页面为操作指引，具体适用应核对现行15 CFR Parts 730–774及许可条件。",
        ["trade", "sales", "procurement", "privacy"],
    ),
    _reference(
        "eu-general-food-law", "欧盟一般食品法（Regulation (EC) 178/2002）",
        "欧洲议会及欧盟理事会 / EUR-Lex", "食品安全与追溯",
        "EU", "欧盟", "欧盟·食品及饲料供应链", "法律法规",
        "规定食品供应链安全责任、批次追溯、撤市与召回的基础规则。",
        ["建立上游供应方和下游企业客户追溯记录，关联批次与标签。", "核验所经营食品满足与活动相关的食品法要求。", "疑似不安全食品离开控制范围时及时启动撤市、告知主管机关；必要时召回。"],
        ["供应商准入", "食材验收", "库存批次", "物流交付", "食品召回"],
        _FOOD_INDUSTRIES,
        "https://eur-lex.europa.eu/legal-content/EN/ALL/?uri=CELEX:32002R0178",
        "适用于食品/饲料生产、加工和分销阶段；私人家庭消费等有范围例外。进口欧盟还需结合具体食品、动物卫生及成员国要求。官方页面可进入现行合并版本。",
        ["quality", "safety", "procurement", "trade"],
    ),
    _reference(
        "eu-food-hygiene", "欧盟食品卫生条例（Regulation (EC) 852/2004）",
        "欧洲议会及欧盟理事会 / EUR-Lex", "食品卫生",
        "EU", "欧盟", "欧盟·食品经营与加工", "法律法规",
        "把良好卫生规范、冷链与HACCP危害控制纳入食品经营过程。",
        ["按业务类型落实场所、设备、个人卫生、温度与冷链控制。", "适用时建立并维护基于HACCP的危害分析、关键限值、监控和纠偏程序。", "保留适合业务规模的文件和记录，发生工艺变更时复核控制。"],
        ["食品生产", "门店卫生", "设备清洗", "冷链仓储", "员工培训"],
        _FOOD_INDUSTRIES,
        "https://eur-lex.europa.eu/legal-content/EN/ALL/?uri=CELEX:32004R0852",
        "初级生产及其相关活动适用专门条款，通常不按第5条要求实施HACCP；私人家庭活动等存在豁免。动物源食品另核对853/2004，成员国可规定登记/批准细则。",
        ["quality", "safety", "people"],
    ),
    _reference(
        "eu-gpsr-product-safety", "欧盟通用产品安全条例（GPSR / Regulation (EU) 2023/988）",
        "欧洲议会及欧盟理事会 / EUR-Lex", "消费品安全",
        "EU", "欧盟", "欧盟·面向消费者的商品", "法律法规",
        "覆盖消费品安全、经营者责任、在线销售信息及危险产品召回。",
        ["识别可合理预见使用风险，形成安全评估及适用的技术资料。", "按制造商、进口商或分销商身份落实产品与经营者标识、警告和追溯。", "在线销售展示必要安全与责任主体信息，建立事故和危险产品处理流程。"],
        ["产品设计", "供应商准入", "商品上架", "质量检验", "产品召回"],
        ["manufacturing", "commerce", "logistics", "general-enterprise"],
        "https://eur-lex.europa.eu/eli/reg/2023/988/oj/eng",
        "自2024-12-13适用，食品、药品等列明产品有排除；已受欧盟专项产品规则覆盖的风险和义务需判断互补适用。向欧盟消费者定向销售的境外商品也应评估，进入官方现行合并版本核对修订。",
        ["quality", "safety", "sales", "trade"], "2024-12-13",
    ),
    _reference(
        "eu-reach-chemicals", "欧盟REACH化学品注册、评估、授权与限制",
        "欧洲化学品管理局 ECHA", "化学品与环境",
        "EU", "欧盟", "欧盟／欧洲经济区·化学品供应链", "监管指引",
        "以物质信息和供应链角色判断化学品注册、风险管理、授权及限制责任。",
        ["建立物质、用途和年度吨位清单，判断制造商、进口商或下游用户责任。", "适用时完成注册及供应链安全信息传递，审查授权和限制清单。", "将化学品合规证据纳入采购准入、配方变更和上市审核。"],
        ["化学品采购", "供应商准入", "产品配方", "物料变更", "进口审核"],
        ["manufacturing", "commerce", "construction", "agriculture", "energy-utilities", "logistics"],
        "https://echa.europa.eu/en-GB/regulations/reach/understanding-reach",
        "注册通常结合角色、豁免和每年1吨门槛判断；限制可能适用于低于注册吨位的物质及物品。部分药品等有豁免，境外企业通常通过欧盟进口商或唯一代表履责。",
        ["environment", "quality", "procurement", "trade", "safety"], "2007-06-01",
    ),
    _reference(
        "eu-nis2-cybersecurity", "欧盟NIS2网络与信息系统安全指令（2022/2555）",
        "欧盟委员会 / DG CONNECT", "网络安全与业务连续性",
        "EU", "欧盟", "欧盟·成员国实施法／关键行业", "监管指引",
        "对关键行业的重要与基本实体提出网络风险管理、供应链安全及重大事件报告要求。",
        ["按行业、规模及指定条件判断是否为受监管实体，核对经营所在成员国实施法。", "建立网络风险、供应链安全、漏洞处置、备份和业务连续性控制。", "明确管理层责任、培训与重大事件识别、升级和报告流程。"],
        ["账号权限", "IT外包", "漏洞管理", "数据备份", "业务连续性", "事件报告"],
        ["saas", "manufacturing", "healthcare", "logistics", "energy-utilities", "food-beverage", "finance-services"],
        "https://digital-strategy.ec.europa.eu/en/policies/nis2-directive",
        "指令须经成员国实施；通常覆盖所列关键领域的中大型实体，部分业务无论规模均可能适用。具体分类、登记和报告要求按所在国家核对；金融等行业还需判断DORA等专项规则关系。",
        ["privacy", "governance", "procurement", "safety"],
    ),
    _reference(
        "uk-data-protection-current", "英国UK GDPR与Data Protection Act（含DUAA 2025修订）",
        "英国信息专员办公室 ICO", "数据与隐私",
        "GB", "英国", "英国·一般个人数据处理", "监管指引",
        "英国一般数据保护体系的现行监管入口，包含2025年数据使用与访问法修订。",
        ["为个人信息处理确定合法依据、提供透明说明并保留责任落实记录。", "设置个人权利响应、数据共享与跨境传输审查、安全及事件处理流程。", "按DUAA现行要求复核投诉渠道及相关制度，跟踪ICO更新指引。"],
        ["客户资料", "员工人事", "隐私告知", "数据共享", "跨境传输", "投诉处理"],
        _ALL_INDUSTRIES,
        "https://ico.org.uk/about-the-ico/what-we-do/legislation-we-cover/data-use-and-access-act-2025/the-data-use-and-access-act-2025-what-does-it-mean-for-organisations/",
        "DUAA修订而非替代UK GDPR、DPA 2018及PECR；ICO于2026-06说明数据保护条款均已生效。须区分一般处理、执法处理及电子营销规则，并依据经营活动和对英国个人提供服务等条件判断适用。",
        ["privacy", "people", "sales", "procurement"],
    ),
    _reference(
        "uk-food-haccp", "英国食品安全管理与HACCP法定义务",
        "英国政府 GOV.UK / 食品标准局 FSA", "食品安全",
        "GB", "英国", "英国·食品经营／属地具体要求", "监管指引",
        "以食品安全管理体系将采购、加工、储存和交付风险落实为日常控制。",
        ["建立满足HACCP原则的食品安全管理体系，识别流程中的食品危害。", "设置可执行的控制、纠偏与记录程序，确保员工理解并持续执行。", "按业务规模选用适合的管理工具，在工艺、菜单或供应变化后复核。"],
        ["食材验收", "食品生产", "门店卫生", "冷链仓储", "食品召回"],
        _FOOD_INDUSTRIES,
        "https://www.gov.uk/food-safety-management-systems",
        "按英格兰、威尔士、苏格兰或北爱尔兰所在地核对现行食品卫生法律及执法机关；初级生产等存在特别规则。小型餐饮可参考简化工具，跨境食品还需核对进口及具体食品要求。",
        ["quality", "safety", "procurement", "people"],
    ),
    _reference(
        "uk-modern-slavery-statement", "英国现代奴役法§54：供应链透明度声明",
        "英国内政部 Home Office", "供应链与劳动权益",
        "GB", "英国", "英国·经营存在／适用规模企业", "监管指引",
        "要求达到条件的商业组织每财年公开说明经营与供应链中防止现代奴役的措施。",
        ["核对组织形态、英国经营存在、商品服务供应及总营业额条件。", "收集供应链和用工风险、措施及效果证据，编制年度声明。", "按组织类型履行批准、签署和公开发布要求，保存版本与审批记录。"],
        ["供应商准入", "外包用工", "劳动权益", "年度披露", "董事会审批"],
        _ALL_INDUSTRIES,
        "https://www.gov.uk/guidance/publish-an-annual-modern-slavery-statement",
        "§54声明义务通常面向在英国经营、供应商品或服务且总年营业额达到£36m的公司/合伙企业等商业组织；包括符合条件的境外组织，总营业额计入子企业。不要把门槛误当作其他反奴役法律的豁免。",
        ["procurement", "people", "governance"],
    ),
    _reference(
        "sg-wsh-risk-management", "新加坡工作场所安全健康法与风险管理规定",
        "新加坡人力部 MOM", "职业安全",
        "SG", "新加坡", "新加坡·工作场所", "监管指引",
        "要求雇主等责任主体识别、控制、监测并沟通工作场所安全健康风险。",
        ["对作业进行风险评估并落实消除或降低风险的措施。", "明确雇主、承包方及场所占用方职责，提供安全设备、培训和监督。", "建立应急措施与风险沟通机制，定期复核风险控制。"],
        ["生产作业", "施工安全", "承包商管理", "设备维护", "员工培训", "应急管理"],
        _WORK_INDUSTRIES,
        "https://www.mom.gov.sg/workplace-safety-and-health/workplace-safety-and-health-act/responsibilities-of-stakeholders",
        "按雇主、占用方、委托方、员工等身份分别判断职责；指导承包方如何作业可能增加相应雇主义务。涉及特定作业需另核对附属规定及许可。",
        ["safety", "people", "procurement"],
    ),
    _reference(
        "sg-food-retail-licensing", "新加坡食品零售许可及供应来源要求",
        "新加坡食品局 SFA", "食品经营许可",
        "SG", "新加坡", "新加坡·餐饮与食品零售", "监管指引",
        "按食品风险和经营场所判断许可，确保餐饮经营与食品供应来源满足SFA要求。",
        ["开业前依据餐馆、食阁、摊位、超市或临时活动类型核对所需许可。", "持牌食品业务只采购符合SFA要求的持牌来源并保留供货证据。", "监控经营范围、经营主体和许可证有效性；变更时评估重新申请。"],
        ["门店开业", "证照管理", "供应商准入", "食材验收", "外包餐饮"],
        ["food-beverage", "commerce", "education", "property", "general-enterprise"],
        "https://www.sfa.gov.sg/food-retail/licence-permit/businesses-that-need-licence-permit-for-food-retail",
        "预包装低风险食品、家庭食品业务及纯中介等可能无需同类零售许可，仍承担食品安全责任。进口、制造、冷藏仓储另有许可；餐饮连锁应逐场所核对，经营许可证不可直接转移。",
        ["quality", "safety", "procurement", "governance"],
    ),
    _reference(
        "sg-fssa-defined-food", "新加坡食品安全与保障法：新型食品等分阶段要求",
        "新加坡食品局 SFA", "食品上市与许可",
        "SG", "新加坡", "新加坡·已生效部分／新型食品等", "监管指引",
        "FSSA分批生效；首批涵盖新型、转基因及特定昆虫食品上市控制和非包装饮用水。",
        ["新产品立项时识别新型食品、转基因食品及昆虫类别是否需要批准。", "上市前收集申请材料、完成所需预上市审批并复核供应限制。", "涉及非包装饮用水服务时核对相应质量与运营责任。"],
        ["新品开发", "产品上市", "供应商准入", "审批许可", "质量检验"],
        ["food-beverage", "agriculture", "manufacturing", "commerce"],
        "https://www.sfa.gov.sg/legislation/food-safety-and-security-act",
        "首批于2025-11-28生效，FSSA整体仍按批次实施。此条目不将尚未生效部分当作现行要求；普通食品经营应同时核对仍适用的既有食品法规和SFA最新实施公告。",
        ["quality", "safety", "procurement", "trade"], "2025-11-28",
    ),
    _reference(
        "jp-food-sanitation-haccp", "日本食品卫生法：基于HACCP的卫生管理",
        "日本厚生劳动省 MHLW", "食品卫生",
        "JP", "日本", "日本·食品经营／部分例外", "监管指引",
        "日本原则上要求食品经营者实施基于HACCP的卫生管理，并通过计划、操作和记录持续复核。",
        ["编制一般卫生与HACCP卫生管理计划，向员工传达要求。", "按需要制定清洁消毒和食品处理操作程序，记录并保存实施情况。", "定期及流程变更后验证计划和程序效果，及时更新。"],
        ["食品生产", "门店卫生", "设备清洗", "食品处理", "员工培训"],
        ["food-beverage", "manufacturing", "commerce", "healthcare", "education"],
        "https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/kenkou_iryou/shokuhin/haccp/index.html",
        "该卫生管理要求自2021-06-01全面实施；食品采集、单纯进口及部分低风险包装食品等存在例外，小规模经营可依行业手册简化执行。进口食品与许可要求另行核对。",
        ["quality", "safety", "people"], "2021-06-01",
    ),
    _reference(
        "au-consumer-guarantees", "澳大利亚消费者法：消费保证与售后救济",
        "澳大利亚竞争与消费者委员会 ACCC", "消费者权益",
        "AU", "澳大利亚", "澳大利亚·消费品与服务／跨境销售", "监管指引",
        "商品和服务自动附带法定消费保证，企业须确保质量及相应售后救济。",
        ["审核产品质量、安全及宣传承诺，避免误导消费保证权利。", "将缺陷判断、维修、更换、退款或取消请求落实为售后处理流程。", "核对保修及退换条款，不用自设期限或免责文字削减法定权利。"],
        ["商品上架", "营销宣传", "质量检验", "客户投诉", "退换货", "售后服务"],
        ["commerce", "manufacturing", "saas", "food-beverage", "professional-services", "education", "general-enterprise"],
        "https://www.accc.gov.au/consumers/buying-products-and-services/consumer-rights-and-guarantees",
        "向澳大利亚消费者直接销售的境外企业亦须评估适用。部分企业采购也可能构成消费，转售、用于生产的商品等有例外；救济按缺陷性质及商品/服务分类判断。",
        ["sales", "quality", "safety", "trade"],
    ),
    _reference(
        "au-whs-jurisdiction", "澳大利亚工作健康安全法（WHS）属地适用索引",
        "澳大利亚安全工作署 Safe Work Australia", "职业安全",
        "AU", "澳大利亚", "澳大利亚·联邦／州／领地", "监管指引",
        "通过属地立法识别企业安全职责，把作业风险防控和员工参与纳入管理。",
        ["确定经营地点及监管机关，取得该州/领地现行WHS或OHS法律。", "按当地规则分配业务经营者和管理人员责任，评估并控制安全健康风险。", "建立员工协商、培训、承包商协调和事故升级记录。"],
        ["生产作业", "施工安全", "员工培训", "承包商管理", "事故报告"],
        _WORK_INDUSTRIES,
        "https://www.safeworkaustralia.gov.au/law-and-regulation/legislation",
        "模型WHS法本身不会自动在各地生效，修订也需属地采纳。多数法域已采纳并存在差异，维多利亚州使用其OHS体系；不得用统一模型替代经营地现行法。",
        ["safety", "people", "procurement", "governance"],
    ),
]
